# Generated by Django 4.1.1 on 2024-03-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_delete_appointment_alter_patient_options_patient_cpf_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
