name: Build - medical-office-manager

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd medical_office_manager/
          pip install -r requirements.txt
          npm ci
          cd ..

      - name: Run local server
        run: |
          pwd
          cd medical_office_manager/
          python manage.py migrate
          python manage.py runserver &
          sleep 5
          npx cypress run

      - name: Cleaning testing files
        run: |
          cd medical_office_manager/
          rm db.sqlite3
          rm cypress.config.js
          rm package-lock.json
          rm package.json
          rm -rf cypress
          rm -rf node_modules
          cd ..

      - name: Zip artifact for deployment
        run: |
          cd medical_office_manager/
          zip release.zip ./* -r
          cd ..
          mv medical_office_manager/release.zip .
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/